### ISSUE TITLE
Excercise 1: Authentication error after generating the service binding

### ISSUE THREAD

**Issue by NikoolaiZim** [SAP-samples/abap-platform-rap-workshops#15]
Excercise 1:
After publishing the service I am not able to see any data in the application. Pressing "Go" in the Travel App leads to the following error: "No authorization to access service group 'ZRAP100_UI_TRAVEL_O4_ZN1'"

Also it get: "You do not have start authorization for R3TR G4BA ZRAP100_UI_TRAVEL_O4_ZN1, return code 4"

**Comment by NikoolaiZim** [comment]
Giving the background jobs time to finish solves the issue.

**Comment by andresj6** [comment]
Hi, did you solved it? how?

**Comment by doldsimo** [comment]
@andresj6 this means you just have wait some time (5-10 minutes) than you will have access

**Comment by NikoolaiZim** [comment]
@doldsimo  yes thanks!

**Comment by Philip014** [comment]
@NikoolaiZim  I am facing the same issue.  Please can you share with us how you resolved the issue?

**Comment by NikoolaiZim** [comment]
@Philip014 Just wait and let the background jobs finish then it worked for me!
