### ISSUE TITLE
abap-platform-rap-workshops/managed_extensibility/

### ISSUE THREAD

**Issue by csramanujan** [SAP-samples/abap-platform-rap-workshops#2]
Hello

In the managed extensibility exercise while creating the class zcl_generate_dev268_0001 for generating the RAP BO I get a syntax error: Type zcl_rap_xco_cloud_lib is unknown. Type: zcx_rap_generator is unknown.

**Comment by jeysonic123** [comment]
Hi, 

We have the same issue "zcl_rap_cxo_cloud_lib" is unknown. This is from example 1 step 6. 

![image](https://user-images.githubusercontent.com/88710773/128837551-9d342a42-5610-481a-a961-20afb2fd7811.png)

**Comment by cocoanut1** [comment]
Same issue as above: No source code provided for zcx_rap_generator and zcl_rap_xco_cloud_lib.

**Comment by anfisc** [comment]
The content of this hands-on has been replaced by this hands on:
https://github.com/SAP-samples/abap-platform-rap-workshops/tree/main/rap6xx/rap620
