### ISSUE TITLE
Generator class cl_gen_rap400_artifacts does not create objects

### ISSUE THREAD

**Issue by mceciabate** [SAP-samples/abap-platform-rap-workshops#22]
Only get 3 objects
![objects](https://github.com/SAP-samples/abap-platform-rap-workshops/assets/93109690/2e2ce058-7fbb-4a80-9bc2-1b4f66ad2163)

**Comment by anfisc** [comment]
I have posted an updated class.
This should work in the trial systems where an updated version of the openSource RAP Generator is available
https://github.com/SAP-samples/abap-platform-rap-workshops/blob/main/rap4xx/rap400/exercises/ex1/sources/ZDMO_gen_rap400_single
