### ISSUE TITLE
RAP generator fails to create artifacts - /dmo/cl_gen_rap400_artifacts

### ISSUE THREAD

**Issue by developedbysom** [SAP-samples/abap-platform-rap-workshops#3]
Hello,

Facing issues while executing class - /dmo/cl_gen_rap400_artifacts to generate required artifacts for continuing ex1. 
This ends up with certain errors:

 **************************************************************************************************** 
 **                    Generation for the RAP400 Workshop (20211018 073633 UTC)                    ** 
 **************************************************************************************************** 
 - Group ID (suffix): 0000 
 - Package: ZRAP400_TRAVEL_0000 (superpackage: ZLOCAL)
 - Transport Request: TRLK901538 
No etag master field found in Travel. etag_master mapped as .
Class name:
/DMO/CX_RAP_GENERATOR
Source position:
Line 219 of VALIDATE_BO in /DMO/CL_RAP_NODE
Stack trace:
CX_XCO_RUNTIME_EXCEPTION    constructor [method] Line: 15
/DMO/CX_RAP_GENERATOR    constructor [method] Line: 1
/DMO/CL_RAP_NODE    validate_bo [method] Line: 219
/DMO/CL_RAP_NODE    finalize [method] Line: 94

Only two DB tables got created with records filled in. 

- Thanks.

**Comment by CarineTD** [comment]
Problem already resolved. Thanks
